#pragma once

#include <types.hh>
#include <util/async.hh>
#include <arch/amd64/amd64.hh>

#define EXPAND(n) exc##n
#define DECL_ISR(n) extern "C" attr_interrupt void EXPAND(n) (cpu_state_amd64_t* i)

pstruct idt_entry_t {
	u16 base0;
	u16 ss;
	u8 ist : 3;
	u8 : 5;
	u8 gate_type : 4;
	u8 : 1;
	u8 dpl : 2;
	u8 present : 1;
	u16 base1;
	u32 base2;
	u32 : 32;
};

pstruct idtr_t {
	u16 size; // size-1
	idt_entry_t* address;
};

DECL_ISR(__COUNTER__); DECL_ISR(__COUNTER__); DECL_ISR(__COUNTER__); DECL_ISR(__COUNTER__);
DECL_ISR(__COUNTER__); DECL_ISR(__COUNTER__); DECL_ISR(__COUNTER__); DECL_ISR(__COUNTER__);
DECL_ISR(__COUNTER__); DECL_ISR(__COUNTER__); DECL_ISR(__COUNTER__); DECL_ISR(__COUNTER__);
DECL_ISR(__COUNTER__); DECL_ISR(__COUNTER__); DECL_ISR(__COUNTER__); DECL_ISR(__COUNTER__);
DECL_ISR(__COUNTER__); DECL_ISR(__COUNTER__); DECL_ISR(__COUNTER__); DECL_ISR(__COUNTER__);
DECL_ISR(__COUNTER__); DECL_ISR(__COUNTER__); DECL_ISR(__COUNTER__); DECL_ISR(__COUNTER__);
DECL_ISR(__COUNTER__); DECL_ISR(__COUNTER__); DECL_ISR(__COUNTER__); DECL_ISR(__COUNTER__);
DECL_ISR(__COUNTER__); DECL_ISR(__COUNTER__); DECL_ISR(__COUNTER__); DECL_ISR(__COUNTER__);
DECL_ISR(__COUNTER__); DECL_ISR(__COUNTER__); DECL_ISR(__COUNTER__); DECL_ISR(__COUNTER__);
DECL_ISR(__COUNTER__); DECL_ISR(__COUNTER__); DECL_ISR(__COUNTER__); DECL_ISR(__COUNTER__);
DECL_ISR(__COUNTER__); DECL_ISR(__COUNTER__); DECL_ISR(__COUNTER__); DECL_ISR(__COUNTER__);
DECL_ISR(__COUNTER__); DECL_ISR(__COUNTER__); DECL_ISR(__COUNTER__); DECL_ISR(__COUNTER__);
DECL_ISR(__COUNTER__); DECL_ISR(__COUNTER__); DECL_ISR(__COUNTER__); DECL_ISR(__COUNTER__);
DECL_ISR(__COUNTER__); DECL_ISR(__COUNTER__); DECL_ISR(__COUNTER__); DECL_ISR(__COUNTER__);
DECL_ISR(__COUNTER__); DECL_ISR(__COUNTER__); DECL_ISR(__COUNTER__); DECL_ISR(__COUNTER__);
DECL_ISR(__COUNTER__); DECL_ISR(__COUNTER__); DECL_ISR(__COUNTER__); DECL_ISR(__COUNTER__);
DECL_ISR(__COUNTER__); DECL_ISR(__COUNTER__); DECL_ISR(__COUNTER__); DECL_ISR(__COUNTER__);
DECL_ISR(__COUNTER__); DECL_ISR(__COUNTER__); DECL_ISR(__COUNTER__); DECL_ISR(__COUNTER__);
DECL_ISR(__COUNTER__); DECL_ISR(__COUNTER__); DECL_ISR(__COUNTER__); DECL_ISR(__COUNTER__);
DECL_ISR(__COUNTER__); DECL_ISR(__COUNTER__); DECL_ISR(__COUNTER__); DECL_ISR(__COUNTER__);
DECL_ISR(__COUNTER__); DECL_ISR(__COUNTER__); DECL_ISR(__COUNTER__); DECL_ISR(__COUNTER__);
DECL_ISR(__COUNTER__); DECL_ISR(__COUNTER__); DECL_ISR(__COUNTER__); DECL_ISR(__COUNTER__);
DECL_ISR(__COUNTER__); DECL_ISR(__COUNTER__); DECL_ISR(__COUNTER__); DECL_ISR(__COUNTER__);
DECL_ISR(__COUNTER__); DECL_ISR(__COUNTER__); DECL_ISR(__COUNTER__); DECL_ISR(__COUNTER__);
DECL_ISR(__COUNTER__); DECL_ISR(__COUNTER__); DECL_ISR(__COUNTER__); DECL_ISR(__COUNTER__);
DECL_ISR(__COUNTER__); DECL_ISR(__COUNTER__); DECL_ISR(__COUNTER__); DECL_ISR(__COUNTER__);
DECL_ISR(__COUNTER__); DECL_ISR(__COUNTER__); DECL_ISR(__COUNTER__); DECL_ISR(__COUNTER__);
DECL_ISR(__COUNTER__); DECL_ISR(__COUNTER__); DECL_ISR(__COUNTER__); DECL_ISR(__COUNTER__);
DECL_ISR(__COUNTER__); DECL_ISR(__COUNTER__); DECL_ISR(__COUNTER__); DECL_ISR(__COUNTER__);
DECL_ISR(__COUNTER__); DECL_ISR(__COUNTER__); DECL_ISR(__COUNTER__); DECL_ISR(__COUNTER__);
DECL_ISR(__COUNTER__); DECL_ISR(__COUNTER__); DECL_ISR(__COUNTER__); DECL_ISR(__COUNTER__);
DECL_ISR(__COUNTER__); DECL_ISR(__COUNTER__); DECL_ISR(__COUNTER__); DECL_ISR(__COUNTER__);
DECL_ISR(__COUNTER__); DECL_ISR(__COUNTER__); DECL_ISR(__COUNTER__); DECL_ISR(__COUNTER__);
DECL_ISR(__COUNTER__); DECL_ISR(__COUNTER__); DECL_ISR(__COUNTER__); DECL_ISR(__COUNTER__);
DECL_ISR(__COUNTER__); DECL_ISR(__COUNTER__); DECL_ISR(__COUNTER__); DECL_ISR(__COUNTER__);
DECL_ISR(__COUNTER__); DECL_ISR(__COUNTER__); DECL_ISR(__COUNTER__); DECL_ISR(__COUNTER__);
DECL_ISR(__COUNTER__); DECL_ISR(__COUNTER__); DECL_ISR(__COUNTER__); DECL_ISR(__COUNTER__);
DECL_ISR(__COUNTER__); DECL_ISR(__COUNTER__); DECL_ISR(__COUNTER__); DECL_ISR(__COUNTER__);
DECL_ISR(__COUNTER__); DECL_ISR(__COUNTER__); DECL_ISR(__COUNTER__); DECL_ISR(__COUNTER__);
DECL_ISR(__COUNTER__); DECL_ISR(__COUNTER__); DECL_ISR(__COUNTER__); DECL_ISR(__COUNTER__);
DECL_ISR(__COUNTER__); DECL_ISR(__COUNTER__); DECL_ISR(__COUNTER__); DECL_ISR(__COUNTER__);
DECL_ISR(__COUNTER__); DECL_ISR(__COUNTER__); DECL_ISR(__COUNTER__); DECL_ISR(__COUNTER__);
DECL_ISR(__COUNTER__); DECL_ISR(__COUNTER__); DECL_ISR(__COUNTER__); DECL_ISR(__COUNTER__);
DECL_ISR(__COUNTER__); DECL_ISR(__COUNTER__); DECL_ISR(__COUNTER__); DECL_ISR(__COUNTER__);
DECL_ISR(__COUNTER__); DECL_ISR(__COUNTER__); DECL_ISR(__COUNTER__); DECL_ISR(__COUNTER__);
DECL_ISR(__COUNTER__); DECL_ISR(__COUNTER__); DECL_ISR(__COUNTER__); DECL_ISR(__COUNTER__);
DECL_ISR(__COUNTER__); DECL_ISR(__COUNTER__); DECL_ISR(__COUNTER__); DECL_ISR(__COUNTER__);
DECL_ISR(__COUNTER__); DECL_ISR(__COUNTER__); DECL_ISR(__COUNTER__); DECL_ISR(__COUNTER__);
DECL_ISR(__COUNTER__); DECL_ISR(__COUNTER__); DECL_ISR(__COUNTER__); DECL_ISR(__COUNTER__);
DECL_ISR(__COUNTER__); DECL_ISR(__COUNTER__); DECL_ISR(__COUNTER__); DECL_ISR(__COUNTER__);
DECL_ISR(__COUNTER__); DECL_ISR(__COUNTER__); DECL_ISR(__COUNTER__); DECL_ISR(__COUNTER__);
DECL_ISR(__COUNTER__); DECL_ISR(__COUNTER__); DECL_ISR(__COUNTER__); DECL_ISR(__COUNTER__);
DECL_ISR(__COUNTER__); DECL_ISR(__COUNTER__); DECL_ISR(__COUNTER__); DECL_ISR(__COUNTER__);
DECL_ISR(__COUNTER__); DECL_ISR(__COUNTER__); DECL_ISR(__COUNTER__); DECL_ISR(__COUNTER__);
DECL_ISR(__COUNTER__); DECL_ISR(__COUNTER__); DECL_ISR(__COUNTER__); DECL_ISR(__COUNTER__);
DECL_ISR(__COUNTER__); DECL_ISR(__COUNTER__); DECL_ISR(__COUNTER__); DECL_ISR(__COUNTER__);
DECL_ISR(__COUNTER__); DECL_ISR(__COUNTER__); DECL_ISR(__COUNTER__); DECL_ISR(__COUNTER__);
DECL_ISR(__COUNTER__); DECL_ISR(__COUNTER__); DECL_ISR(__COUNTER__); DECL_ISR(__COUNTER__);
DECL_ISR(__COUNTER__); DECL_ISR(__COUNTER__); DECL_ISR(__COUNTER__); DECL_ISR(__COUNTER__);
DECL_ISR(__COUNTER__); DECL_ISR(__COUNTER__); DECL_ISR(__COUNTER__); DECL_ISR(__COUNTER__);
DECL_ISR(__COUNTER__); DECL_ISR(__COUNTER__); DECL_ISR(__COUNTER__); DECL_ISR(__COUNTER__);
DECL_ISR(__COUNTER__); DECL_ISR(__COUNTER__); DECL_ISR(__COUNTER__); DECL_ISR(__COUNTER__);
DECL_ISR(__COUNTER__); DECL_ISR(__COUNTER__); DECL_ISR(__COUNTER__); DECL_ISR(__COUNTER__);
DECL_ISR(__COUNTER__); DECL_ISR(__COUNTER__); DECL_ISR(__COUNTER__); DECL_ISR(__COUNTER__);

static_assert(__COUNTER__ == 256);

#define loop(stuff, n)

extern atomic<u64> tmr_counter;

void arch_idt_init();
u8 idt_allocate_vector(void (*handlerfun)(cpu_state_amd64_t* frame));
void idt_deallocate_vector(u8 vector);
