#pragma once

enum irqs {
	IRQ_PIT = 0,
	IRQ_PS2_KB = 1,
	IRQ_PIC_CASCADE = 2,
	IRQ_COM2 = 3,
	IRQ_COM1 = 4,
	IRQ_LPT2 = 5,
	IRQ_FLOPPY = 6,
	IRQ_LPT2_SPUR = 7,
	IRQ_RTC = 8,
	IRQ_LEGACY_SCSI = 9,
	IRQ_SCSI1 = 10,
	IRQ_SCSI2 = 11,
	IRQ_PS2_MOUSE = 12,
	IRQ_COPROC = 13,
	IRQ_PRIM_ATA_DRIVE = 14,
	IRQ_SECOND_ATA_DRIVE = 15,
};
